name: pre-merge check

on: 
  push:
    branches:
    - master
    - develop
    - feature/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  cmake-build:
    name: cmake build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04, ubuntu-20.04]
        go-version: ['^1.20.0', '^1.21.0']

    steps:
    - uses: actions/checkout@v3
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: ubuntu-install
      if: runner.os == 'Linux'
      run: |
        sudo apt install opensc-pkcs11
    - name: go build
      run: go build
