name: pre-merge check

on: 
  push:
    branches:
    - master
    - develop
    - feature/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  cmake-build:
    name: cmake build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, ubuntu-16.04]
        go-version: [1.12.x, 1.13.x, 1.15.x]

    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v1
    - name: ubuntu-install
      if: runner.os != 'macOS'
      run: |
        sudo apt install opensc-pkcs11
    - name: cmake
      run: |
        cmake --version
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DTARGET_RPATH="./build/Release"
        make
        cd ..
    - name: go build
      run: go build
