name: create-release-upload

on: 
  push:
    tags:
    - 'v*'

jobs:
  upload-object-alpine:
    name: upload-object-alpine
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: list
      run: ls -a $GITHUB_WORKSPACE
    - name: docker setup
      uses: docker://alpine:3.10
      with:
        entrypoint: /github/workspace/.github/workflows/docker/alpine_build_entrypoint.sh
    - name: create archive file
      run: |
        echo "---- dump output data ----"
        ls -l $GITHUB_WORKSPACE/dist/usr/local/*
        mkdir -p /tmp/cloudhsm
        sudo chmod 777 /tmp/cloudhsm
        sudo chown runner /tmp/cloudhsm
        sudo cp -r $GITHUB_WORKSPACE/dist/usr /tmp/cloudhsm
        cd /tmp/cloudhsm
        sudo zip -r /tmp/cloudhsm/cloudhsm.zip usr
        sudo chmod 777 /tmp/cloudhsm/cloudhsm.zip
        sudo chown runner /tmp/cloudhsm/cloudhsm.zip
        sudo cp -rp /tmp/cloudhsm/cloudhsm.zip $GITHUB_WORKSPACE/dist/cloudhsm.zip
        echo "---- dump zip file ----"
        sudo ls -l /tmp/cloudhsm
    - name: pre-release-test
      uses: docker://golang:1.13-alpine
      with:
        entrypoint: /github/workspace/.github/workflows/docker/alpine_test_entrypoint.sh
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
#      continue-on-error: true
    - name: Upload Release Asset
      id: upload-release-asset 
#      if: success()
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/cloudhsm/cloudhsm.zip
        asset_name: cloudhsm-${{ steps.get_version.outputs.VERSION }}-alpine_x86_64.zip
        asset_content_type: application/zip
    - name: write upload url
      env:
        url: ${{ steps.create_release.outputs.upload_url }}
      run: |
        cd /tmp/cloudhsm
        sudo echo $url > upload_url.txt
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact-upload_url
        path: /tmp/cloudhsm/upload_url.txt

  upload-object-ubuntu:
    name: upload-object-ubuntu
    needs: upload-object-alpine
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04]

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: list
      run: ls -a $GITHUB_WORKSPACE
    - name: cmake-build
      id: cmake_build
      run: |
        sudo rm -rf build
        mkdir build
        cd build
        cmake --version
        cmake .. -DENABLE_SHARED=on -DCMAKE_BUILD_TYPE=Release -DTARGET_RPATH="/usr/local/lib"
        make
        cd ..
        export CURRENT_DIR=$(pwd)
        echo ::set-output name=CURRENT_DIR::$CURRENT_DIR
    - name: cmake-install
      run: |
        sudo rm -rf dist
        mkdir dist
        cd build
        make install DESTDIR=../dist
        cd ..
    - name: create archive file
      run: |
        cd dist
        zip -r cloudhsm.zip usr
        echo "---- dump zip file ----"
        ls -l
    - name: download artifact
      uses: actions/download-artifact@v1
      with:
        name: artifact-upload_url
    - name: dump upload url
      id: get_url
      run: |
        url=$(cat artifact-upload_url/upload_url.txt)
        echo ::set-output name=upload_url::$url
    - name: Upload Release Asset Ubuntu-18.04
      if: matrix.os == 'ubuntu-18.04'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./dist/cloudhsm.zip
        asset_name: cloudhsm-${{ steps.get_version.outputs.VERSION }}-ubuntu1804-gcc-x86_64.zip
        asset_content_type: application/zip
    - name: Upload Release Asset Ubuntu-16.04
      if: matrix.os == 'ubuntu-16.04'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_url.outputs.upload_url }}
        asset_path: ./dist/cloudhsm.zip
        asset_name: cloudhsm-${{ steps.get_version.outputs.VERSION }}-ubuntu1604-gcc-x86_64.zip
        asset_content_type: application/zip
